- hosts: loadbalancer
  tasks:
   - name: "Installing Haproxy"
     package:
      name: "haproxy"
      state: present
   - name: "Copying the Haproxy Configuration file"
     template:
      src: haproxy.cfg
      dest: /etc/haproxy/haproxy.cfg
   - name: "Exposing the Proxy to port 8080"
     firewalld:
      port: 8080/tcp
      state: enabled
      permanent: yes
      immediate: yes
   - name: "Starting Haproxy"
     service: 
      name: haproxy
      state: restarted
